using System.Globalization;
using System.IO.Compression;
using System.Security;
using System.Text;
using PersonalProject.Models.DTOs;

namespace PersonalProject.Utilities
{
    public static class ClinicAdminReportBuilder
    {
        // =====================================================
        // CSV
        // =====================================================

        public static byte[] BuildCsv(
            ClinicAdminReportDataDto report
        )
        {
            var builder =
                new StringBuilder();

            Csv(
                builder,
                "PhilaLink Clinic Report"
            );

            Csv(
                builder,
                "Clinic",
                report.ClinicName
            );

            Csv(
                builder,
                "Generated by",
                report.AdminName
            );

            Csv(
                builder,
                "Generated at",
                DateTimeText(
                    report.GeneratedAtUtc
                )
            );

            Csv(
                builder,
                "Range",
                $"{DateText(report.RangeStartUtc)} - {DateText(report.RangeEndUtc)}"
            );

            builder.AppendLine();

            Csv(
                builder,
                "SUMMARY"
            );

            Csv(
                builder,
                "Metric",
                "Value"
            );

            var kpis =
                report.Analytics.Kpis;

            Csv(
                builder,
                "Active patients",
                kpis.ActivePatients
            );

            Csv(
                builder,
                "Active nurses",
                kpis.ActiveNurses
            );

            Csv(
                builder,
                "Active proxies",
                kpis.ActiveProxies
            );

            Csv(
                builder,
                "Appointments today",
                kpis.AppointmentsToday
            );

            Csv(
                builder,
                "Pending appointments",
                kpis.PendingAppointments
            );

            Csv(
                builder,
                "Collections due today",
                kpis.CollectionsDueToday
            );

            Csv(
                builder,
                "Overdue collections",
                kpis.OverdueCollections
            );

            Csv(
                builder,
                "Low stock items",
                kpis.LowStockItems
            );

            Csv(
                builder,
                "Collected this month",
                kpis.CollectedThisMonth
            );

            Csv(
                builder,
                "New patients this month",
                kpis.NewPatientsThisMonth
            );

            builder.AppendLine();

            Csv(
                builder,
                "APPOINTMENTS"
            );

            Csv(
                builder,
                "Scheduled",
                "Patient",
                "Type",
                "Mode",
                "Status",
                "Nurse"
            );

            foreach (
                var item in
                    report.Appointments
            )
            {
                Csv(
                    builder,
                    DateTimeText(
                        item.ScheduledAt
                    ),
                    item.PatientName,
                    item.Type,
                    item.Mode,
                    item.Status,
                    item.NurseName
                );
            }

            builder.AppendLine();

            Csv(
                builder,
                "COLLECTIONS"
            );

            Csv(
                builder,
                "Scheduled",
                "Collected",
                "Patient",
                "Status",
                "Proxy",
                "Processed by",
                "Quantity"
            );

            foreach (
                var item in
                    report.Collections
            )
            {
                Csv(
                    builder,
                    DateTimeText(
                        item.ScheduledCollectionDate
                    ),
                    item.CollectedAt.HasValue
                        ? DateTimeText(
                            item.CollectedAt.Value
                        )
                        : "",
                    item.PatientName,
                    item.Status,
                    item.ProxyName,
                    item.ProcessedByNurseName,
                    item.TotalQuantity
                );
            }

            builder.AppendLine();

            Csv(
                builder,
                "INVENTORY"
            );

            Csv(
                builder,
                "Medication",
                "Strength",
                "Form",
                "Unit",
                "Quantity",
                "Reorder level",
                "Status",
                "Active"
            );

            foreach (
                var item in
                    report.Inventory
            )
            {
                Csv(
                    builder,
                    item.MedicationName,
                    item.Strength,
                    item.Form,
                    item.Unit,
                    item.QuantityOnHand,
                    item.ReorderLevel,
                    item.Status,
                    item.IsActive
                        ? "Yes"
                        : "No"
                );
            }

            builder.AppendLine();

            Csv(
                builder,
                "STAFF"
            );

            Csv(
                builder,
                "Full name",
                "Role",
                "ID number",
                "Phone",
                "Email",
                "Active",
                "Created"
            );

            foreach (
                var item in
                    report.Staff
            )
            {
                Csv(
                    builder,
                    item.FullName,
                    item.Role,
                    item.IdNumber,
                    item.PhoneNumber,
                    item.Email,
                    item.IsActive
                        ? "Yes"
                        : "No",
                    DateTimeText(
                        item.CreatedAt
                    )
                );
            }

            builder.AppendLine();

            Csv(
                builder,
                "NEW PATIENTS"
            );

            Csv(
                builder,
                "Full name",
                "Patient number",
                "Phone",
                "Registered"
            );

            foreach (
                var item in
                    report.NewPatients
            )
            {
                Csv(
                    builder,
                    item.FullName,
                    item.PatientNumber,
                    item.PhoneNumber,
                    DateTimeText(
                        item.CreatedAt
                    )
                );
            }

            var body =
                Encoding.UTF8.GetBytes(
                    builder.ToString()
                );

            var bom =
                Encoding.UTF8.GetPreamble();

            var output =
                new byte[
                    bom.Length +
                    body.Length
                ];

            Buffer.BlockCopy(
                bom,
                0,
                output,
                0,
                bom.Length
            );

            Buffer.BlockCopy(
                body,
                0,
                output,
                bom.Length,
                body.Length
            );

            return output;
        }

        // =====================================================
        // XLSX
        // =====================================================

        public static byte[] BuildXlsx(
            ClinicAdminReportDataDto report
        )
        {
            var sheets =
                new List<SheetDefinition>
                {
                    new(
                        "Summary",
                        SummaryRows(
                            report
                        )
                    ),

                    new(
                        "Appointments",
                        AppointmentRows(
                            report
                        )
                    ),

                    new(
                        "Collections",
                        CollectionRows(
                            report
                        )
                    ),

                    new(
                        "Inventory",
                        InventoryRows(
                            report
                        )
                    ),

                    new(
                        "Staff",
                        StaffRows(
                            report
                        )
                    ),

                    new(
                        "New Patients",
                        PatientRows(
                            report
                        )
                    )
                };

            using var memory =
                new MemoryStream();

            using (
                var archive =
                    new ZipArchive(
                        memory,
                        ZipArchiveMode.Create,
                        true
                    )
            )
            {
                WriteEntry(
                    archive,
                    "[Content_Types].xml",
                    ContentTypes(
                        sheets.Count
                    )
                );

                WriteEntry(
                    archive,
                    "_rels/.rels",
                    """
                    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                    <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                      <Relationship Id="rId1"
                        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
                        Target="xl/workbook.xml"/>
                    </Relationships>
                    """
                );

                WriteEntry(
                    archive,
                    "xl/workbook.xml",
                    Workbook(
                        sheets
                    )
                );

                WriteEntry(
                    archive,
                    "xl/_rels/workbook.xml.rels",
                    WorkbookRelationships(
                        sheets.Count
                    )
                );

                WriteEntry(
                    archive,
                    "xl/styles.xml",
                    Styles()
                );

                for (
                    var index = 0;
                    index <
                        sheets.Count;
                    index++
                )
                {
                    WriteEntry(
                        archive,
                        $"xl/worksheets/sheet{index + 1}.xml",
                        Worksheet(
                            sheets[index]
                                .Rows
                        )
                    );
                }
            }

            return memory.ToArray();
        }

        // =====================================================
        // PDF
        // =====================================================

        public static byte[] BuildPdf(
            ClinicAdminReportDataDto report
        )
        {
            var sourceLines =
                BuildPdfLines(
                    report
                );

            var lines =
                new List<string>();

            foreach (
                var line in
                    sourceLines
            )
            {
                lines.AddRange(
                    Wrap(
                        line,
                        90
                    )
                );
            }

            var pages =
                lines
                    .Chunk(
                        48
                    )
                    .Select(
                        page =>
                            page.ToList()
                    )
                    .ToList();

            if (
                pages.Count ==
                0
            )
            {
                pages.Add(
                    new List<string>
                    {
                        "PhilaLink Clinic Report"
                    }
                );
            }

            return SimplePdf(
                pages
            );
        }

        // =====================================================
        // ROW BUILDERS
        // =====================================================

        private static List<List<object?>>
            SummaryRows(
                ClinicAdminReportDataDto report
            )
        {
            var kpis =
                report.Analytics.Kpis;

            return new()
            {
                new()
                {
                    "PhilaLink Clinic Report"
                },

                new()
                {
                    "Clinic",
                    report.ClinicName
                },

                new()
                {
                    "Generated by",
                    report.AdminName
                },

                new()
                {
                    "Generated at",
                    DateTimeText(
                        report.GeneratedAtUtc
                    )
                },

                new()
                {
                    "Range start",
                    DateText(
                        report.RangeStartUtc
                    )
                },

                new()
                {
                    "Range end",
                    DateText(
                        report.RangeEndUtc
                    )
                },

                new(),

                new()
                {
                    "Metric",
                    "Value"
                },

                new()
                {
                    "Active patients",
                    kpis.ActivePatients
                },

                new()
                {
                    "Active nurses",
                    kpis.ActiveNurses
                },

                new()
                {
                    "Active proxies",
                    kpis.ActiveProxies
                },

                new()
                {
                    "Appointments today",
                    kpis.AppointmentsToday
                },

                new()
                {
                    "Pending appointments",
                    kpis.PendingAppointments
                },

                new()
                {
                    "Collections due today",
                    kpis.CollectionsDueToday
                },

                new()
                {
                    "Overdue collections",
                    kpis.OverdueCollections
                },

                new()
                {
                    "Low stock items",
                    kpis.LowStockItems
                },

                new()
                {
                    "Collected this month",
                    kpis.CollectedThisMonth
                },

                new()
                {
                    "New patients this month",
                    kpis.NewPatientsThisMonth
                }
            };
        }

        private static List<List<object?>>
            AppointmentRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Scheduled",
                        "Patient",
                        "Type",
                        "Mode",
                        "Status",
                        "Nurse"
                    }
                };

            foreach (
                var item in
                    report.Appointments
            )
            {
                rows.Add(
                    new()
                    {
                        DateTimeText(
                            item.ScheduledAt
                        ),

                        item.PatientName,

                        item.Type,

                        item.Mode,

                        item.Status,

                        item.NurseName
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            CollectionRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Scheduled",
                        "Collected",
                        "Patient",
                        "Status",
                        "Proxy",
                        "Processed by",
                        "Quantity"
                    }
                };

            foreach (
                var item in
                    report.Collections
            )
            {
                rows.Add(
                    new()
                    {
                        DateTimeText(
                            item.ScheduledCollectionDate
                        ),

                        item.CollectedAt.HasValue
                            ? DateTimeText(
                                item.CollectedAt.Value
                            )
                            : "",

                        item.PatientName,

                        item.Status,

                        item.ProxyName,

                        item.ProcessedByNurseName,

                        item.TotalQuantity
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            InventoryRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Medication",
                        "Strength",
                        "Form",
                        "Unit",
                        "Quantity",
                        "Reorder level",
                        "Status",
                        "Active"
                    }
                };

            foreach (
                var item in
                    report.Inventory
            )
            {
                rows.Add(
                    new()
                    {
                        item.MedicationName,

                        item.Strength,

                        item.Form,

                        item.Unit,

                        item.QuantityOnHand,

                        item.ReorderLevel,

                        item.Status,

                        item.IsActive
                            ? "Yes"
                            : "No"
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            StaffRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Full name",
                        "Role",
                        "ID number",
                        "Phone",
                        "Email",
                        "Active",
                        "Created"
                    }
                };

            foreach (
                var item in
                    report.Staff
            )
            {
                rows.Add(
                    new()
                    {
                        item.FullName,

                        item.Role,

                        item.IdNumber,

                        item.PhoneNumber,

                        item.Email,

                        item.IsActive
                            ? "Yes"
                            : "No",

                        DateTimeText(
                            item.CreatedAt
                        )
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            PatientRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Full name",
                        "Patient number",
                        "Phone",
                        "Registered"
                    }
                };

            foreach (
                var item in
                    report.NewPatients
            )
            {
                rows.Add(
                    new()
                    {
                        item.FullName,

                        item.PatientNumber,

                        item.PhoneNumber,

                        DateTimeText(
                            item.CreatedAt
                        )
                    }
                );
            }

            return rows;
        }

        // =====================================================
        // XLSX XML
        // =====================================================

        private static string ContentTypes(
            int sheetCount
        )
        {
            var sheets =
                new StringBuilder();

            for (
                var index = 1;
                index <=
                    sheetCount;
                index++
            )
            {
                sheets.Append(
                    $"""
                    <Override PartName="/xl/worksheets/sheet{index}.xml"
                      ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
                    """
                );
            }

            return
                $"""
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                  <Default Extension="rels"
                    ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                  <Default Extension="xml"
                    ContentType="application/xml"/>
                  <Override PartName="/xl/workbook.xml"
                    ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
                  <Override PartName="/xl/styles.xml"
                    ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
                  {sheets}
                </Types>
                """;
        }

        private static string Workbook(
            IReadOnlyList<SheetDefinition>
                sheets
        )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <workbook
                  xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
                  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
                  <sheets>
                """
            );

            for (
                var index = 0;
                index <
                    sheets.Count;
                index++
            )
            {
                builder.Append(
                    $"""
                    <sheet
                      name="{Xml(sheets[index].Name)}"
                      sheetId="{index + 1}"
                      r:id="rId{index + 1}"/>
                    """
                );
            }

            builder.Append(
                """
                  </sheets>
                </workbook>
                """
            );

            return builder.ToString();
        }

        private static string
            WorkbookRelationships(
                int sheetCount
            )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                """
            );

            for (
                var index = 1;
                index <=
                    sheetCount;
                index++
            )
            {
                builder.Append(
                    $"""
                    <Relationship
                      Id="rId{index}"
                      Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"
                      Target="worksheets/sheet{index}.xml"/>
                    """
                );
            }

            builder.Append(
                $"""
                <Relationship
                  Id="rId{sheetCount + 1}"
                  Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
                  Target="styles.xml"/>
                </Relationships>
                """
            );

            return builder.ToString();
        }

        private static string Styles()
        {
            return
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                  <fonts count="1">
                    <font>
                      <sz val="11"/>
                      <name val="Calibri"/>
                    </font>
                  </fonts>
                  <fills count="2">
                    <fill><patternFill patternType="none"/></fill>
                    <fill><patternFill patternType="gray125"/></fill>
                  </fills>
                  <borders count="1">
                    <border/>
                  </borders>
                  <cellStyleXfs count="1">
                    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
                  </cellStyleXfs>
                  <cellXfs count="1">
                    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
                  </cellXfs>
                  <cellStyles count="1">
                    <cellStyle name="Normal" xfId="0" builtinId="0"/>
                  </cellStyles>
                </styleSheet>
                """;
        }

        private static string Worksheet(
            IReadOnlyList<List<object?>>
                rows
        )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                  <sheetData>
                """
            );

            for (
                var rowIndex = 0;
                rowIndex <
                    rows.Count;
                rowIndex++
            )
            {
                var excelRow =
                    rowIndex + 1;

                builder.Append(
                    $"<row r=\"{excelRow}\">"
                );

                for (
                    var columnIndex = 0;
                    columnIndex <
                        rows[rowIndex].Count;
                    columnIndex++
                )
                {
                    Cell(
                        builder,
                        $"{Column(columnIndex + 1)}{excelRow}",
                        rows[rowIndex][columnIndex]
                    );
                }

                builder.Append(
                    "</row>"
                );
            }

            builder.Append(
                """
                  </sheetData>
                </worksheet>
                """
            );

            return builder.ToString();
        }

        private static void Cell(
            StringBuilder builder,
            string reference,
            object? value
        )
        {
            if (
                value == null
            )
            {
                builder.Append(
                    $"<c r=\"{reference}\"/>"
                );

                return;
            }

            if (
                value is byte ||
                value is short ||
                value is int ||
                value is long ||
                value is float ||
                value is double ||
                value is decimal
            )
            {
                builder.Append(
                    $"<c r=\"{reference}\"><v>{Convert.ToString(value, CultureInfo.InvariantCulture)}</v></c>"
                );

                return;
            }

            builder.Append(
                $"<c r=\"{reference}\" t=\"inlineStr\"><is><t>{Xml(ValueText(value))}</t></is></c>"
            );
        }

        private static string Column(
            int index
        )
        {
            var value =
                string.Empty;

            while (
                index > 0
            )
            {
                index--;

                value =
                    (char)(
                        'A' +
                        index %
                        26
                    ) +
                    value;

                index /=
                    26;
            }

            return value;
        }

        private static void WriteEntry(
            ZipArchive archive,
            string name,
            string content
        )
        {
            var entry =
                archive.CreateEntry(
                    name,
                    CompressionLevel.Fastest
                );

            using var stream =
                entry.Open();

            using var writer =
                new StreamWriter(
                    stream,
                    new UTF8Encoding(
                        false
                    )
                );

            writer.Write(
                content
            );
        }

        // =====================================================
        // PDF
        // =====================================================

        private static List<string>
            BuildPdfLines(
                ClinicAdminReportDataDto report
            )
        {
            var kpis =
                report.Analytics.Kpis;

            var lines =
                new List<string>
                {
                    "PHILALINK CLINIC OPERATIONS REPORT",
                    "",
                    $"Clinic: {report.ClinicName}",
                    $"Generated by: {report.AdminName}",
                    $"Generated: {DateTimeText(report.GeneratedAtUtc)}",
                    $"Range: {DateText(report.RangeStartUtc)} - {DateText(report.RangeEndUtc)}",
                    "",
                    "SUMMARY",
                    $"Active patients: {kpis.ActivePatients}",
                    $"Active nurses: {kpis.ActiveNurses}",
                    $"Active proxies: {kpis.ActiveProxies}",
                    $"Appointments today: {kpis.AppointmentsToday}",
                    $"Pending appointments: {kpis.PendingAppointments}",
                    $"Collections due today: {kpis.CollectionsDueToday}",
                    $"Overdue collections: {kpis.OverdueCollections}",
                    $"Low stock items: {kpis.LowStockItems}",
                    $"Collected this month: {kpis.CollectedThisMonth}",
                    $"New patients this month: {kpis.NewPatientsThisMonth}",
                    "",
                    "APPOINTMENTS"
                };

            foreach (
                var item in
                    report.Appointments
            )
            {
                lines.Add(
                    $"{DateTimeText(item.ScheduledAt)} | {item.PatientName} | {item.Type} | {item.Status} | {item.NurseName}"
                );
            }

            lines.Add("");
            lines.Add(
                "COLLECTIONS"
            );

            foreach (
                var item in
                    report.Collections
            )
            {
                lines.Add(
                    $"{DateTimeText(item.ScheduledCollectionDate)} | {item.PatientName} | {item.Status} | Quantity {item.TotalQuantity}"
                );
            }

            lines.Add("");
            lines.Add(
                "INVENTORY"
            );

            foreach (
                var item in
                    report.Inventory
            )
            {
                lines.Add(
                    $"{item.MedicationName} {item.Strength} | {item.QuantityOnHand} {item.Unit} | Reorder {item.ReorderLevel} | {item.Status}"
                );
            }

            lines.Add("");
            lines.Add(
                "STAFF"
            );

            foreach (
                var item in
                    report.Staff
            )
            {
                lines.Add(
                    $"{item.FullName} | {item.Role} | {(item.IsActive ? "Active" : "Inactive")}"
                );
            }

            lines.Add("");
            lines.Add(
                "NEW PATIENTS"
            );

            foreach (
                var item in
                    report.NewPatients
            )
            {
                lines.Add(
                    $"{item.FullName} | {item.PatientNumber} | {DateText(item.CreatedAt)}"
                );
            }

            return lines;
        }

        private static byte[] SimplePdf(
            IReadOnlyList<List<string>>
                pages
        )
        {
            using var stream =
                new MemoryStream();

            var offsets =
                new List<long>
                {
                    0
                };

            void WriteAscii(
                string value
            )
            {
                var bytes =
                    Encoding.ASCII.GetBytes(
                        value
                    );

                stream.Write(
                    bytes,
                    0,
                    bytes.Length
                );
            }

            WriteAscii(
                "%PDF-1.4\n"
            );

            var objectCount =
                3 +
                pages.Count *
                2;

            var pageIds =
                Enumerable
                    .Range(
                        0,
                        pages.Count
                    )
                    .Select(
                        index =>
                            4 +
                            index *
                            2
                    )
                    .ToList();

            var objects =
                new Dictionary<int, string>
                {
                    [1] =
                        "<< /Type /Catalog /Pages 2 0 R >>",

                    [2] =
                        $"<< /Type /Pages /Kids [{string.Join(" ", pageIds.Select(id => $"{id} 0 R"))}] /Count {pages.Count} >>",

                    [3] =
                        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
                };

            for (
                var index = 0;
                index <
                    pages.Count;
                index++
            )
            {
                var pageId =
                    4 +
                    index *
                    2;

                var contentId =
                    pageId + 1;

                var content =
                    PdfPage(
                        pages[index]
                    );

                objects[pageId] =
                    $"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {contentId} 0 R >>";

                objects[contentId] =
                    $"<< /Length {Encoding.ASCII.GetByteCount(content)} >>\nstream\n{content}\nendstream";
            }

            for (
                var id = 1;
                id <=
                    objectCount;
                id++
            )
            {
                offsets.Add(
                    stream.Position
                );

                WriteAscii(
                    $"{id} 0 obj\n{objects[id]}\nendobj\n"
                );
            }

            var xref =
                stream.Position;

            WriteAscii(
                $"xref\n0 {objectCount + 1}\n"
            );

            WriteAscii(
                "0000000000 65535 f \n"
            );

            for (
                var id = 1;
                id <=
                    objectCount;
                id++
            )
            {
                WriteAscii(
                    $"{offsets[id]:D10} 00000 n \n"
                );
            }

            WriteAscii(
                $"trailer\n<< /Size {objectCount + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF"
            );

            return stream.ToArray();
        }

        private static string PdfPage(
            IReadOnlyList<string>
                lines
        )
        {
            var builder =
                new StringBuilder();

            builder.AppendLine(
                "BT"
            );

            builder.AppendLine(
                "/F1 9 Tf"
            );

            builder.AppendLine(
                "40 750 Td"
            );

            builder.AppendLine(
                "14 TL"
            );

            foreach (
                var line in
                    lines
            )
            {
                builder.Append(
                    "("
                );

                builder.Append(
                    EscapePdf(
                        Ascii(
                            line
                        )
                    )
                );

                builder.AppendLine(
                    ") Tj"
                );

                builder.AppendLine(
                    "T*"
                );
            }

            builder.Append(
                "ET"
            );

            return builder.ToString();
        }

        private static IEnumerable<string>
            Wrap(
                string text,
                int maximum
            )
        {
            if (
                string.IsNullOrEmpty(
                    text
                )
            )
            {
                yield return "";
                yield break;
            }

            var remaining =
                text.Trim();

            while (
                remaining.Length >
                    maximum
            )
            {
                var split =
                    remaining.LastIndexOf(
                        ' ',
                        maximum
                    );

                if (
                    split <= 0
                )
                {
                    split =
                        maximum;
                }

                yield return
                    remaining[
                        ..split
                    ];

                remaining =
                    remaining[
                        split..
                    ]
                    .Trim();
            }

            yield return
                remaining;
        }

        // =====================================================
        // COMMON
        // =====================================================

        private static void Csv(
            StringBuilder builder,
            params object?[] values
        )
        {
            builder.AppendLine(
                string.Join(
                    ",",
                    values.Select(
                        CsvValue
                    )
                )
            );
        }

        private static string CsvValue(
            object? value
        )
        {
            var text =
                ValueText(
                    value
                )
                .Replace(
                    "\"",
                    "\"\""
                );

            return
                $"\"{text}\"";
        }

        private static string ValueText(
            object? value
        )
        {
            return value switch
            {
                null =>
                    "",

                DateTime date =>
                    DateTimeText(
                        date
                    ),

                bool boolean =>
                    boolean
                        ? "Yes"
                        : "No",

                IFormattable valueFormatter =>
                    valueFormatter.ToString(
                        null,
                        CultureInfo.InvariantCulture
                    ) ??
                    "",

                _ =>
                    value.ToString() ??
                    ""
            };
        }

        private static string Xml(
            string value
        )
        {
            return
                SecurityElement.Escape(
                    value
                ) ??
                "";
        }

        private static string EscapePdf(
            string value
        )
        {
            return value
                .Replace(
                    "\\",
                    "\\\\"
                )
                .Replace(
                    "(",
                    "\\("
                )
                .Replace(
                    ")",
                    "\\)"
                );
        }

        private static string Ascii(
            string value
        )
        {
            var builder =
                new StringBuilder(
                    value.Length
                );

            foreach (
                var character in
                    value
            )
            {
                builder.Append(
                    character <=
                    127
                        ? character
                        : '?'
                );
            }

            return builder.ToString();
        }

        private static string DateText(
            DateTime value
        )
        {
            return value.ToString(
                "yyyy-MM-dd",
                CultureInfo.InvariantCulture
            );
        }

        private static string DateTimeText(
            DateTime value
        )
        {
            return value.ToString(
                "yyyy-MM-dd HH:mm",
                CultureInfo.InvariantCulture
            );
        }

        private sealed record
            SheetDefinition(
                string Name,
                List<List<object?>> Rows
            );
    }
}