using System.Globalization;
using System.IO.Compression;
using System.Security;
using System.Text;
using PersonalProject.Models.DTOs;

namespace PersonalProject.Utilities
{
    public static class ClinicAdminReportBuilder
    {
        // =====================================================
        // CSV
        // =====================================================

        public static byte[] BuildCsv(
            ClinicAdminReportDataDto report
        )
        {
            var builder =
                new StringBuilder();

            AppendCsvRow(
                builder,
                "PhilaLink Clinic Report"
            );

            AppendCsvRow(
                builder,
                "Clinic",
                report.ClinicName
            );

            AppendCsvRow(
                builder,
                "Generated by",
                report.AdminName
            );

            AppendCsvRow(
                builder,
                "Generated at",
                FormatDateTime(
                    report.GeneratedAtUtc
                )
            );

            AppendCsvRow(
                builder,
                "Report range",
                $"{FormatDate(report.RangeStartUtc)} - {FormatDate(report.RangeEndUtc)}"
            );

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "SUMMARY"
            );

            AppendCsvRow(
                builder,
                "Metric",
                "Value"
            );

            var kpis =
                report.Analytics.Kpis;

            AppendCsvRow(
                builder,
                "Active patients",
                kpis.ActivePatients
            );

            AppendCsvRow(
                builder,
                "Active nurses",
                kpis.ActiveNurses
            );

            AppendCsvRow(
                builder,
                "Active proxies",
                kpis.ActiveProxies
            );

            AppendCsvRow(
                builder,
                "Appointments today",
                kpis.AppointmentsToday
            );

            AppendCsvRow(
                builder,
                "Pending appointments",
                kpis.PendingAppointments
            );

            AppendCsvRow(
                builder,
                "Collections due today",
                kpis.CollectionsDueToday
            );

            AppendCsvRow(
                builder,
                "Overdue collections",
                kpis.OverdueCollections
            );

            AppendCsvRow(
                builder,
                "Low stock items",
                kpis.LowStockItems
            );

            AppendCsvRow(
                builder,
                "Collected this month",
                kpis.CollectedThisMonth
            );

            AppendCsvRow(
                builder,
                "New patients this month",
                kpis.NewPatientsThisMonth
            );

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "APPOINTMENTS"
            );

            AppendCsvRow(
                builder,
                "Scheduled At",
                "Patient",
                "Type",
                "Mode",
                "Status",
                "Nurse"
            );

            foreach (
                var item in
                    report.Appointments
            )
            {
                AppendCsvRow(
                    builder,
                    FormatDateTime(
                        item.ScheduledAt
                    ),
                    item.PatientName,
                    item.Type,
                    item.Mode,
                    item.Status,
                    item.NurseName
                );
            }

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "MEDICATION COLLECTIONS"
            );

            AppendCsvRow(
                builder,
                "Scheduled",
                "Collected",
                "Patient",
                "Status",
                "Proxy",
                "Processed by Nurse",
                "Total Quantity"
            );

            foreach (
                var item in
                    report.Collections
            )
            {
                AppendCsvRow(
                    builder,
                    FormatDateTime(
                        item.ScheduledCollectionDate
                    ),
                    item.CollectedAt ==
                        null
                        ? ""
                        : FormatDateTime(
                            item.CollectedAt.Value
                        ),
                    item.PatientName,
                    item.Status,
                    item.ProxyName,
                    item.ProcessedByNurseName,
                    item.TotalQuantity
                );
            }

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "INVENTORY"
            );

            AppendCsvRow(
                builder,
                "Medication",
                "Strength",
                "Form",
                "Unit",
                "Quantity",
                "Reorder Level",
                "Status",
                "Active"
            );

            foreach (
                var item in
                    report.Inventory
            )
            {
                AppendCsvRow(
                    builder,
                    item.MedicationName,
                    item.Strength,
                    item.Form,
                    item.Unit,
                    item.QuantityOnHand,
                    item.ReorderLevel,
                    item.Status,
                    item.IsActive
                        ? "Yes"
                        : "No"
                );
            }

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "STAFF"
            );

            AppendCsvRow(
                builder,
                "Full Name",
                "Role",
                "ID Number",
                "Phone",
                "Email",
                "Active",
                "Created"
            );

            foreach (
                var item in
                    report.Staff
            )
            {
                AppendCsvRow(
                    builder,
                    item.FullName,
                    item.Role,
                    item.IdNumber,
                    item.PhoneNumber,
                    item.Email,
                    item.IsActive
                        ? "Yes"
                        : "No",
                    FormatDateTime(
                        item.CreatedAt
                    )
                );
            }

            builder.AppendLine();

            AppendCsvRow(
                builder,
                "NEW PATIENTS"
            );

            AppendCsvRow(
                builder,
                "Full Name",
                "Patient Number",
                "Phone",
                "Registered"
            );

            foreach (
                var item in
                    report.NewPatients
            )
            {
                AppendCsvRow(
                    builder,
                    item.FullName,
                    item.PatientNumber,
                    item.PhoneNumber,
                    FormatDateTime(
                        item.CreatedAt
                    )
                );
            }

            /*
             * UTF-8 BOM makes Excel recognise the CSV encoding
             * reliably when opened directly.
             */
            var preamble =
                Encoding.UTF8
                    .GetPreamble();

            var body =
                Encoding.UTF8
                    .GetBytes(
                        builder.ToString()
                    );

            var result =
                new byte[
                    preamble.Length +
                    body.Length
                ];

            Buffer.BlockCopy(
                preamble,
                0,
                result,
                0,
                preamble.Length
            );

            Buffer.BlockCopy(
                body,
                0,
                result,
                preamble.Length,
                body.Length
            );

            return result;
        }

        // =====================================================
        // XLSX
        // =====================================================

        public static byte[] BuildXlsx(
            ClinicAdminReportDataDto report
        )
        {
            var sheets =
                new List<
                    (
                        string Name,
                        List<List<object?>> Rows
                    )
                >
                {
                    (
                        "Summary",
                        BuildSummaryRows(
                            report
                        )
                    ),

                    (
                        "Appointments",
                        BuildAppointmentRows(
                            report
                        )
                    ),

                    (
                        "Collections",
                        BuildCollectionRows(
                            report
                        )
                    ),

                    (
                        "Inventory",
                        BuildInventoryRows(
                            report
                        )
                    ),

                    (
                        "Staff",
                        BuildStaffRows(
                            report
                        )
                    ),

                    (
                        "New Patients",
                        BuildPatientRows(
                            report
                        )
                    )
                };

            using var memory =
                new MemoryStream();

            using (
                var archive =
                    new ZipArchive(
                        memory,
                        ZipArchiveMode.Create,
                        true
                    )
            )
            {
                WriteZipEntry(
                    archive,
                    "[Content_Types].xml",
                    BuildContentTypes(
                        sheets.Count
                    )
                );

                WriteZipEntry(
                    archive,
                    "_rels/.rels",
                    """
                    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                    <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                      <Relationship
                        Id="rId1"
                        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
                        Target="xl/workbook.xml"/>
                    </Relationships>
                    """
                );

                WriteZipEntry(
                    archive,
                    "xl/workbook.xml",
                    BuildWorkbook(
                        sheets
                    )
                );

                WriteZipEntry(
                    archive,
                    "xl/_rels/workbook.xml.rels",
                    BuildWorkbookRelationships(
                        sheets.Count
                    )
                );

                WriteZipEntry(
                    archive,
                    "xl/styles.xml",
                    BuildStyles()
                );

                for (
                    var index = 0;
                    index <
                        sheets.Count;
                    index++
                )
                {
                    WriteZipEntry(
                        archive,
                        $"xl/worksheets/sheet{index + 1}.xml",
                        BuildWorksheet(
                            sheets[index]
                                .Rows
                        )
                    );
                }
            }

            return memory.ToArray();
        }

        private static List<List<object?>>
            BuildSummaryRows(
                ClinicAdminReportDataDto report
            )
        {
            var kpis =
                report.Analytics.Kpis;

            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "PhilaLink Clinic Report"
                    },

                    new()
                    {
                        "Clinic",
                        report.ClinicName
                    },

                    new()
                    {
                        "Generated by",
                        report.AdminName
                    },

                    new()
                    {
                        "Generated at",
                        FormatDateTime(
                            report.GeneratedAtUtc
                        )
                    },

                    new()
                    {
                        "Range start",
                        FormatDate(
                            report.RangeStartUtc
                        )
                    },

                    new()
                    {
                        "Range end",
                        FormatDate(
                            report.RangeEndUtc
                        )
                    },

                    new(),

                    new()
                    {
                        "Metric",
                        "Value"
                    },

                    new()
                    {
                        "Active patients",
                        kpis.ActivePatients
                    },

                    new()
                    {
                        "Active nurses",
                        kpis.ActiveNurses
                    },

                    new()
                    {
                        "Active proxies",
                        kpis.ActiveProxies
                    },

                    new()
                    {
                        "Appointments today",
                        kpis.AppointmentsToday
                    },

                    new()
                    {
                        "Pending appointments",
                        kpis.PendingAppointments
                    },

                    new()
                    {
                        "Collections due today",
                        kpis.CollectionsDueToday
                    },

                    new()
                    {
                        "Overdue collections",
                        kpis.OverdueCollections
                    },

                    new()
                    {
                        "Low stock items",
                        kpis.LowStockItems
                    },

                    new()
                    {
                        "Collected this month",
                        kpis.CollectedThisMonth
                    },

                    new()
                    {
                        "New patients this month",
                        kpis.NewPatientsThisMonth
                    }
                };

            return rows;
        }

        private static List<List<object?>>
            BuildAppointmentRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Scheduled At",
                        "Patient",
                        "Type",
                        "Mode",
                        "Status",
                        "Nurse"
                    }
                };

            foreach (
                var item in
                    report.Appointments
            )
            {
                rows.Add(
                    new()
                    {
                        FormatDateTime(
                            item.ScheduledAt
                        ),

                        item.PatientName,

                        item.Type,

                        item.Mode,

                        item.Status,

                        item.NurseName
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            BuildCollectionRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Scheduled",
                        "Collected",
                        "Patient",
                        "Status",
                        "Proxy",
                        "Processed by Nurse",
                        "Total Quantity"
                    }
                };

            foreach (
                var item in
                    report.Collections
            )
            {
                rows.Add(
                    new()
                    {
                        FormatDateTime(
                            item.ScheduledCollectionDate
                        ),

                        item.CollectedAt ==
                            null
                            ? ""
                            : FormatDateTime(
                                item.CollectedAt.Value
                            ),

                        item.PatientName,

                        item.Status,

                        item.ProxyName,

                        item.ProcessedByNurseName,

                        item.TotalQuantity
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            BuildInventoryRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Medication",
                        "Strength",
                        "Form",
                        "Unit",
                        "Quantity",
                        "Reorder Level",
                        "Status",
                        "Active"
                    }
                };

            foreach (
                var item in
                    report.Inventory
            )
            {
                rows.Add(
                    new()
                    {
                        item.MedicationName,

                        item.Strength,

                        item.Form,

                        item.Unit,

                        item.QuantityOnHand,

                        item.ReorderLevel,

                        item.Status,

                        item.IsActive
                            ? "Yes"
                            : "No"
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            BuildStaffRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Full Name",
                        "Role",
                        "ID Number",
                        "Phone",
                        "Email",
                        "Active",
                        "Created"
                    }
                };

            foreach (
                var item in
                    report.Staff
            )
            {
                rows.Add(
                    new()
                    {
                        item.FullName,

                        item.Role,

                        item.IdNumber,

                        item.PhoneNumber,

                        item.Email,

                        item.IsActive
                            ? "Yes"
                            : "No",

                        FormatDateTime(
                            item.CreatedAt
                        )
                    }
                );
            }

            return rows;
        }

        private static List<List<object?>>
            BuildPatientRows(
                ClinicAdminReportDataDto report
            )
        {
            var rows =
                new List<List<object?>>
                {
                    new()
                    {
                        "Full Name",
                        "Patient Number",
                        "Phone",
                        "Registered"
                    }
                };

            foreach (
                var item in
                    report.NewPatients
            )
            {
                rows.Add(
                    new()
                    {
                        item.FullName,

                        item.PatientNumber,

                        item.PhoneNumber,

                        FormatDateTime(
                            item.CreatedAt
                        )
                    }
                );
            }

            return rows;
        }

        private static string BuildContentTypes(
            int sheetCount
        )
        {
            var sheets =
                new StringBuilder();

            for (
                var i = 1;
                i <= sheetCount;
                i++
            )
            {
                sheets.Append(
                    $"""
                    <Override
                      PartName="/xl/worksheets/sheet{i}.xml"
                      ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
                    """
                );
            }

            return
                $"""
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                  <Default
                    Extension="rels"
                    ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                  <Default
                    Extension="xml"
                    ContentType="application/xml"/>
                  <Override
                    PartName="/xl/workbook.xml"
                    ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
                  <Override
                    PartName="/xl/styles.xml"
                    ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
                  {sheets}
                </Types>
                """;
        }

        private static string BuildWorkbook(
            IReadOnlyList<
                (
                    string Name,
                    List<List<object?>> Rows
                )
            > sheets
        )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <workbook
                  xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
                  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
                  <sheets>
                """
            );

            for (
                var index = 0;
                index <
                    sheets.Count;
                index++
            )
            {
                builder.Append(
                    $"""
                    <sheet
                      name="{XmlEscape(sheets[index].Name)}"
                      sheetId="{index + 1}"
                      r:id="rId{index + 1}"/>
                    """
                );
            }

            builder.Append(
                """
                  </sheets>
                </workbook>
                """
            );

            return builder.ToString();
        }

        private static string
            BuildWorkbookRelationships(
                int sheetCount
            )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                """
            );

            for (
                var i = 1;
                i <= sheetCount;
                i++
            )
            {
                builder.Append(
                    $"""
                    <Relationship
                      Id="rId{i}"
                      Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"
                      Target="worksheets/sheet{i}.xml"/>
                    """
                );
            }

            builder.Append(
                $"""
                <Relationship
                  Id="rId{sheetCount + 1}"
                  Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
                  Target="styles.xml"/>
                </Relationships>
                """
            );

            return builder.ToString();
        }

        private static string BuildStyles()
        {
            return
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                  <fonts count="1">
                    <font>
                      <sz val="11"/>
                      <name val="Calibri"/>
                    </font>
                  </fonts>
                  <fills count="2">
                    <fill>
                      <patternFill patternType="none"/>
                    </fill>
                    <fill>
                      <patternFill patternType="gray125"/>
                    </fill>
                  </fills>
                  <borders count="1">
                    <border/>
                  </borders>
                  <cellStyleXfs count="1">
                    <xf
                      numFmtId="0"
                      fontId="0"
                      fillId="0"
                      borderId="0"/>
                  </cellStyleXfs>
                  <cellXfs count="1">
                    <xf
                      numFmtId="0"
                      fontId="0"
                      fillId="0"
                      borderId="0"
                      xfId="0"/>
                  </cellXfs>
                  <cellStyles count="1">
                    <cellStyle
                      name="Normal"
                      xfId="0"
                      builtinId="0"/>
                  </cellStyles>
                </styleSheet>
                """;
        }

        private static string BuildWorksheet(
            IReadOnlyList<
                List<object?>
            > rows
        )
        {
            var builder =
                new StringBuilder();

            builder.Append(
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
                  <sheetData>
                """
            );

            for (
                var rowIndex = 0;
                rowIndex <
                    rows.Count;
                rowIndex++
            )
            {
                var excelRow =
                    rowIndex + 1;

                builder.Append(
                    $"<row r=\"{excelRow}\">"
                );

                var row =
                    rows[rowIndex];

                for (
                    var columnIndex = 0;
                    columnIndex <
                        row.Count;
                    columnIndex++
                )
                {
                    var reference =
                        $"{ColumnName(columnIndex + 1)}{excelRow}";

                    AppendExcelCell(
                        builder,
                        reference,
                        row[columnIndex]
                    );
                }

                builder.Append(
                    "</row>"
                );
            }

            builder.Append(
                """
                  </sheetData>
                </worksheet>
                """
            );

            return builder.ToString();
        }

        private static void AppendExcelCell(
            StringBuilder builder,
            string reference,
            object? value
        )
        {
            if (value == null)
            {
                builder.Append(
                    $"<c r=\"{reference}\"/>"
                );

                return;
            }

            switch (value)
            {
                case byte number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case short number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case int number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case long number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case float number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case double number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                case decimal number:
                    AppendNumberCell(
                        builder,
                        reference,
                        number
                    );
                    break;

                default:
                    builder.Append(
                        $"<c r=\"{reference}\" t=\"inlineStr\"><is><t>{XmlEscape(FormatValue(value))}</t></is></c>"
                    );
                    break;
            }
        }

        private static void AppendNumberCell(
            StringBuilder builder,
            string reference,
            object number
        )
        {
            builder.Append(
                $"<c r=\"{reference}\"><v>{Convert.ToString(number, CultureInfo.InvariantCulture)}</v></c>"
            );
        }

        private static string ColumnName(
            int column
        )
        {
            var result =
                string.Empty;

            while (
                column > 0
            )
            {
                column--;

                result =
                    (char)(
                        'A' +
                        column % 26
                    ) +
                    result;

                column /= 26;
            }

            return result;
        }

        private static void WriteZipEntry(
            ZipArchive archive,
            string path,
            string content
        )
        {
            var entry =
                archive.CreateEntry(
                    path,
                    CompressionLevel.Fastest
                );

            using var stream =
                entry.Open();

            using var writer =
                new StreamWriter(
                    stream,
                    new UTF8Encoding(
                        false
                    )
                );

            writer.Write(
                content
            );
        }

        // =====================================================
        // PDF
        // =====================================================

        public static byte[] BuildPdf(
            ClinicAdminReportDataDto report
        )
        {
            var lines =
                BuildPdfLines(
                    report
                );

            var wrapped =
                new List<string>();

            foreach (
                var line in lines
            )
            {
                wrapped.AddRange(
                    WrapText(
                        line,
                        92
                    )
                );
            }

            const int linesPerPage =
                48;

            var pages =
                wrapped
                    .Chunk(
                        linesPerPage
                    )
                    .Select(
                        page =>
                            page.ToList()
                    )
                    .ToList();

            if (
                pages.Count == 0
            )
            {
                pages.Add(
                    new List<string>
                    {
                        "PhilaLink Clinic Report"
                    }
                );
            }

            return BuildSimplePdf(
                pages
            );
        }

        private static List<string>
            BuildPdfLines(
                ClinicAdminReportDataDto report
            )
        {
            var kpis =
                report.Analytics.Kpis;

            var lines =
                new List<string>
                {
                    "PHILALINK CLINIC OPERATIONS REPORT",
                    "",
                    $"Clinic: {report.ClinicName}",
                    $"Generated by: {report.AdminName}",
                    $"Generated: {FormatDateTime(report.GeneratedAtUtc)}",
                    $"Range: {FormatDate(report.RangeStartUtc)} - {FormatDate(report.RangeEndUtc)}",
                    "",
                    "SUMMARY",
                    $"Active patients: {kpis.ActivePatients}",
                    $"Active nurses: {kpis.ActiveNurses}",
                    $"Active proxies: {kpis.ActiveProxies}",
                    $"Appointments today: {kpis.AppointmentsToday}",
                    $"Pending appointments: {kpis.PendingAppointments}",
                    $"Collections due today: {kpis.CollectionsDueToday}",
                    $"Overdue collections: {kpis.OverdueCollections}",
                    $"Low stock items: {kpis.LowStockItems}",
                    $"Collected this month: {kpis.CollectedThisMonth}",
                    $"New patients this month: {kpis.NewPatientsThisMonth}",
                    "",
                    "APPOINTMENTS"
                };

            foreach (
                var item in
                    report.Appointments
            )
            {
                lines.Add(
                    $"{FormatDateTime(item.ScheduledAt)} | {item.PatientName} | {item.Type} | {item.Status} | {item.NurseName}"
                );
            }

            lines.Add("");
            lines.Add(
                "MEDICATION COLLECTIONS"
            );

            foreach (
                var item in
                    report.Collections
            )
            {
                lines.Add(
                    $"{FormatDateTime(item.ScheduledCollectionDate)} | {item.PatientName} | {item.Status} | Qty {item.TotalQuantity}"
                );
            }

            lines.Add("");
            lines.Add(
                "INVENTORY"
            );

            foreach (
                var item in
                    report.Inventory
            )
            {
                lines.Add(
                    $"{item.MedicationName} {item.Strength} | {item.QuantityOnHand} {item.Unit} | Reorder {item.ReorderLevel} | {item.Status}"
                );
            }

            lines.Add("");
            lines.Add(
                "STAFF"
            );

            foreach (
                var item in
                    report.Staff
            )
            {
                lines.Add(
                    $"{item.FullName} | {item.Role} | {(item.IsActive ? "Active" : "Inactive")}"
                );
            }

            lines.Add("");
            lines.Add(
                "NEW PATIENTS"
            );

            foreach (
                var item in
                    report.NewPatients
            )
            {
                lines.Add(
                    $"{item.FullName} | {item.PatientNumber} | {FormatDate(item.CreatedAt)}"
                );
            }

            return lines;
        }

        private static byte[] BuildSimplePdf(
            IReadOnlyList<
                List<string>
            > pages
        )
        {
            using var stream =
                new MemoryStream();

            var offsets =
                new List<long>
                {
                    0
                };

            void WriteAscii(
                string text
            )
            {
                var bytes =
                    Encoding.ASCII
                        .GetBytes(
                            text
                        );

                stream.Write(
                    bytes,
                    0,
                    bytes.Length
                );
            }

            WriteAscii(
                "%PDF-1.4\n"
            );

            var objectCount =
                3 +
                pages.Count * 2;

            var pageObjectIds =
                new List<int>();

            for (
                var i = 0;
                i <
                    pages.Count;
                i++
            )
            {
                pageObjectIds.Add(
                    4 + i * 2
                );
            }

            var objects =
                new Dictionary<
                    int,
                    string
                >();

            objects[1] =
                "<< /Type /Catalog /Pages 2 0 R >>";

            objects[2] =
                $"<< /Type /Pages /Kids [{string.Join(" ", pageObjectIds.Select(id => $"{id} 0 R"))}] /Count {pages.Count} >>";

            objects[3] =
                "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

            for (
                var i = 0;
                i <
                    pages.Count;
                i++
            )
            {
                var pageId =
                    4 + i * 2;

                var contentId =
                    pageId + 1;

                var content =
                    BuildPdfPageContent(
                        pages[i]
                    );

                var contentLength =
                    Encoding.ASCII
                        .GetByteCount(
                            content
                        );

                objects[pageId] =
                    $"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {contentId} 0 R >>";

                objects[contentId] =
                    $"<< /Length {contentLength} >>\nstream\n{content}\nendstream";
            }

            for (
                var id = 1;
                id <= objectCount;
                id++
            )
            {
                offsets.Add(
                    stream.Position
                );

                WriteAscii(
                    $"{id} 0 obj\n{objects[id]}\nendobj\n"
                );
            }

            var xrefOffset =
                stream.Position;

            WriteAscii(
                $"xref\n0 {objectCount + 1}\n"
            );

            WriteAscii(
                "0000000000 65535 f \n"
            );

            for (
                var id = 1;
                id <= objectCount;
                id++
            )
            {
                WriteAscii(
                    $"{offsets[id]:D10} 00000 n \n"
                );
            }

            WriteAscii(
                $"trailer\n<< /Size {objectCount + 1} /Root 1 0 R >>\nstartxref\n{xrefOffset}\n%%EOF"
            );

            return stream.ToArray();
        }

        private static string
            BuildPdfPageContent(
                IReadOnlyList<string>
                    lines
            )
        {
            var builder =
                new StringBuilder();

            builder.AppendLine(
                "BT"
            );

            builder.AppendLine(
                "/F1 9 Tf"
            );

            builder.AppendLine(
                "40 750 Td"
            );

            builder.AppendLine(
                "14 TL"
            );

            foreach (
                var line in
                    lines
            )
            {
                builder.Append(
                    "("
                );

                builder.Append(
                    EscapePdfText(
                        ToAscii(
                            line
                        )
                    )
                );

                builder.AppendLine(
                    ") Tj"
                );

                builder.AppendLine(
                    "T*"
                );
            }

            builder.Append(
                "ET"
            );

            return builder.ToString();
        }

        private static IEnumerable<string>
            WrapText(
                string value,
                int maxLength
            )
        {
            if (
                string.IsNullOrEmpty(
                    value
                )
            )
            {
                yield return
                    string.Empty;

                yield break;
            }

            var remaining =
                value.Trim();

            while (
                remaining.Length >
                    maxLength
            )
            {
                var split =
                    remaining.LastIndexOf(
                        ' ',
                        maxLength
                    );

                if (
                    split <= 0
                )
                {
                    split =
                        maxLength;
                }

                yield return
                    remaining[
                        ..split
                    ];

                remaining =
                    remaining[
                        split..
                    ]
                    .Trim();
            }

            yield return
                remaining;
        }

        // =====================================================
        // COMMON
        // =====================================================

        private static void AppendCsvRow(
            StringBuilder builder,
            params object?[] values
        )
        {
            builder.AppendLine(
                string.Join(
                    ",",
                    values.Select(
                        CsvEscape
                    )
                )
            );
        }

        private static string CsvEscape(
            object? value
        )
        {
            var text =
                FormatValue(
                    value
                );

            text =
                text.Replace(
                    "\"",
                    "\"\""
                );

            return
                $"\"{text}\"";
        }

        private static string FormatValue(
            object? value
        )
        {
            return value switch
            {
                null =>
                    string.Empty,

                DateTime date =>
                    FormatDateTime(
                        date
                    ),

                bool boolean =>
                    boolean
                        ? "Yes"
                        : "No",

                IFormattable formattable =>
                    formattable.ToString(
                        null,
                        CultureInfo
                            .InvariantCulture
                    ) ??
                    string.Empty,

                _ =>
                    value.ToString() ??
                    string.Empty
            };
        }

        private static string XmlEscape(
            string value
        )
        {
            return
                SecurityElement.Escape(
                    value
                ) ??
                string.Empty;
        }

        private static string EscapePdfText(
            string value
        )
        {
            return value
                .Replace(
                    "\\",
                    "\\\\"
                )
                .Replace(
                    "(",
                    "\\("
                )
                .Replace(
                    ")",
                    "\\)"
                );
        }

        private static string ToAscii(
            string value
        )
        {
            var builder =
                new StringBuilder(
                    value.Length
                );

            foreach (
                var character in
                    value
            )
            {
                builder.Append(
                    character <= 127
                        ? character
                        : '?'
                );
            }

            return builder.ToString();
        }

        private static string FormatDate(
            DateTime value
        )
        {
            return value.ToString(
                "yyyy-MM-dd",
                CultureInfo.InvariantCulture
            );
        }

        private static string FormatDateTime(
            DateTime value
        )
        {
            return value.ToString(
                "yyyy-MM-dd HH:mm",
                CultureInfo.InvariantCulture
            );
        }
    }
}